-- =============================================================
-- Food Safety Audit Report — Migración completa para Supabase
-- PostgreSQL compatible · Tipos corregidos
-- =============================================================

-- ⚠️ Si las tablas ya existen con errores, ejecutar primero:
-- DROP TABLE IF EXISTS audit_cip_flows CASCADE;
-- DROP TABLE IF EXISTS audit_evidence_images CASCADE;
-- DROP TABLE IF EXISTS audit_cop_findings CASCADE;
-- DROP TABLE IF EXISTS audit_section_params CASCADE;
-- DROP TABLE IF EXISTS food_safety_audit_reports CASCADE;

-- 1. Tabla principal
CREATE TABLE IF NOT EXISTS food_safety_audit_reports (
  id                      BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  folio                   VARCHAR(30)  NOT NULL UNIQUE,

  -- Datos de la portada
  cliente_empresa         VARCHAR(200) NOT NULL,
  -- Almacenamos como texto porque el formato es "Mayo, 2026", no una fecha ISO
  fecha_auditoria         VARCHAR(100) NOT NULL,
  location_of_audit       VARCHAR(300),
  llenadora               VARCHAR(100) NOT NULL,
  llenadora_serial        VARCHAR(100),
  llenadora_horas_op      DECIMAL(10,2),

  -- Personas a cargo (array de objetos JSON)
  personas_a_cargo        JSONB DEFAULT '[]'::jsonb,

  -- Autorización SIG Combibloc
  autorizacion_sig_nombre  VARCHAR(200),
  autorizacion_sig_puesto  VARCHAR(200),
  autorizacion_sig_empresa VARCHAR(200),
  autorizacion_sig_firma   VARCHAR(500),

  -- Autorización Cliente
  autorizacion_cliente_nombre  VARCHAR(200),
  autorizacion_cliente_puesto  VARCHAR(200),
  autorizacion_cliente_empresa VARCHAR(200),
  autorizacion_cliente_firma   VARCHAR(500),

  -- Estado y metadata
  estado           VARCHAR(20) CHECK (estado IN ('borrador','en_revision','finalizado')) DEFAULT 'borrador',
  observaciones_gen TEXT,

  -- ✅ UUID: el user.id de Supabase Auth siempre es UUID, nunca un número
  auditor_id       UUID,

  created_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  
  -- Añadir Foreign Key para poder hacer JOIN con usuarios
  CONSTRAINT fk_auditor_usuario FOREIGN KEY (auditor_id) REFERENCES usuarios(id) ON DELETE SET NULL
);

-- 2. Parámetros técnicos (HH / HS / SP / L / LL)
CREATE TABLE IF NOT EXISTS audit_section_params (
  id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  audit_id       BIGINT       NOT NULL,
  seccion        VARCHAR(60)  NOT NULL,
  subseccion     VARCHAR(100),
  feature        VARCHAR(255) NOT NULL,
  unidad         VARCHAR(30),
  valor_hh       DECIMAL(10,3),
  valor_hs       DECIMAL(10,3),
  valor_sp       DECIMAL(10,3),
  valor_l        DECIMAL(10,3),
  valor_ll       DECIMAL(10,3),
  ultimo_valor   DECIMAL(10,3),
  valor_actual   DECIMAL(10,3),
  -- ✅ dentro_rango lo calculamos en la app (evita problemas con NULL en columnas generadas)
  dentro_rango   BOOLEAN DEFAULT NULL,
  observacion    TEXT,
  track          SMALLINT DEFAULT NULL,
  created_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (audit_id) REFERENCES food_safety_audit_reports(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_audit_params ON audit_section_params(audit_id, seccion);

-- 3. Hallazgos COP
CREATE TABLE IF NOT EXISTS audit_cop_findings (
  id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  audit_id     BIGINT       NOT NULL,
  seccion_cop  VARCHAR(100) NOT NULL,
  cam_on       DECIMAL(6,2),
  cam_off      DECIMAL(6,2),
  descripcion  TEXT,
  tiene_falla  BOOLEAN DEFAULT FALSE,
  created_at   TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (audit_id) REFERENCES food_safety_audit_reports(id) ON DELETE CASCADE
);

-- 4. Imágenes de evidencia
CREATE TABLE IF NOT EXISTS audit_evidence_images (
  id              BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  audit_id        BIGINT       NOT NULL,
  cop_finding_id  BIGINT       DEFAULT NULL,
  param_id        BIGINT       DEFAULT NULL,
  storage_key     VARCHAR(500) NOT NULL,
  url_original    VARCHAR(1000),
  url_thumbnail   VARCHAR(1000),
  url_report      VARCHAR(1000),
  nombre_archivo  VARCHAR(255),
  mime_type       VARCHAR(50),
  size_bytes      INT,
  width_px        INT,
  height_px       INT,
  caption         VARCHAR(500),
  orden           SMALLINT DEFAULT 0,
  uploaded_at     TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (audit_id)        REFERENCES food_safety_audit_reports(id) ON DELETE CASCADE,
  FOREIGN KEY (cop_finding_id)  REFERENCES audit_cop_findings(id)        ON DELETE CASCADE,
  FOREIGN KEY (param_id)        REFERENCES audit_section_params(id)      ON DELETE CASCADE
);

-- 5. Flujos CIP
CREATE TABLE IF NOT EXISTS audit_cip_flows (
  id                BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  audit_id          BIGINT   NOT NULL,
  -- ✅ ENUM como VARCHAR + CHECK (más robusto en Supabase que ENUM nativo)
  paso              VARCHAR(50) CHECK (paso IN ('pre_rinsing','otros')) NOT NULL,
  track             SMALLINT NOT NULL,
  cabezal           SMALLINT NOT NULL,
  tipo_cabezal      VARCHAR(100),
  flujo_ml_s        DECIMAL(8,3),
  volumen_total_hmi DECIMAL(10,3),
  volumen_total_cip DECIMAL(10,3),
  FOREIGN KEY (audit_id) REFERENCES food_safety_audit_reports(id) ON DELETE CASCADE
);
